services:
  service-bus:
    ports:
      - "5672:5672"
      - "5300:5300"
  
  servicebus-db:
    ports:
      - "1433:1433"

  servicebus-api:
    ports:
      - "80:80"

  azurite:
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  signalr:
    ports:
      - "8888:8888"

configs:
  signalr:
    file: ./dev/config/signalr.json