services:
  service-bus:
    container_name: servicebus
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    # pull_policy: always
    volumes:
      - "./dev/config/servicebus.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: servicebus-db
      MSSQL_SA_PASSWORD: "MasterPassw0rd"  # Password should be same as what is set for SQL Edge
      ACCEPT_EULA: Y
      #SQL_WAIT_INTERVAL: ${SQL_WAIT_INTERVAL} # Optional: Time in seconds to wait for SQL to be ready (default is 15 seconds)
    depends_on:
      - servicebus-db
  
  servicebus-db:
    container_name: servicebus-db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      MSSQL_PID: 'Express'
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "MasterPassw0rd"
  
  servicebus-api:
    container_name: servicebus-api
    build:
      context: ./dev/asbapi
    volumes:
      - "./dev/config/servicebus.json:/config/config.json"
    ports:
      - "80:8080"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  signalr:
    container_name: signalr
    build:
      context: ./dev/asrs
    volumes:
      - "./dev/config/signalr.json:/emulator/settings.json"
    ports:
      - "8888:8888"
