include:
  - ../../docker-compose.yaml

services:
  cloud:
    depends_on:
      superbus-worker:
        condition: service_healthy
    build:
      context: ./SuperBus.Samples.Simple.Cloud
    environment:
      "SuperBus__Connection": "Endpoint=sb://servicebus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
      "SuperBus__StoragePrefix": "superbus-sample-simple"
  
  superbus-worker:
    build:
      context: ../../src/workers/src/SuperBus.SuperBusWorker
    depends_on:
      servicebus-health:
        condition: service_healthy
      azurite-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/admin/host/status?code=master-secret"]
      interval: 5s
      timeout: 5s
      retries: 5
    configs:
      - source: azfunctions-secrets
        target: /azure-functions-host/Secrets/host.json
    environment:
      # Use the full Azurite connection string as we need to change the host
      "AzureWebJobsStorage": "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;"
      "AzureSignalRConnectionString": "Endpoint=http://signalr;Port=8888;AccessKey=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGH;Version=1.0;"
      "ServiceBusConnection": "Endpoint=sb://servicebus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
      "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"
      "SuperBus__StoragePrefix": "superbus-sample-simple"
      "OpenId__Authority": "http://superbus-worker/api"
      "Logging__LogLevel__Default": "Debug"
      "AzureWebJobsSecretStorageType": files

  tenant-a-connector-a:
    depends_on:
      superbus-worker:
        condition: service_healthy
    build:
      context: ./SuperBus.Samples.Simple.Connector
    environment:
      "SuperBus__Endpoint": "http://superbus-worker/api"
      "SuperBus__ConnectorId": "connector-a"
      "SuperBus__TenantId": "tenant-a"
      "SuperBus__SigningKey": "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgGZfhjhITuJz0BkkS3yYezLelZOm1Lhma4/owsRcj6kuhRANCAAQNJ+AiJ4ZpVMXtEtGijQcf/FSODdPyMevVGTF5EGrDLuUAYEbpjg+eWRrSqpUBGvHdNW4weGZFJCe7Up8WAqe4"
      "SuperBus__StoragePrefix": "superbus-sample-simple"
  
  tenant-a-connector-b:
    depends_on:
      superbus-worker:
        condition: service_healthy
    build:
      context: ./SuperBus.Samples.Simple.Connector
    environment:
      "SuperBus__Endpoint": "http://superbus-worker/api"
      "SuperBus__ConnectorId": "connector-b"
      "SuperBus__TenantId": "tenant-a"
      "SuperBus__SigningKey": "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgwER5qy7vlJWRS8mYGVq9Xs1SiCsFEnAMZTkteXuRZyOhRANCAAQvfIiC9wb0LKvO/UpTSmv9HGt/g3rgwQONgtd4hi6mcVd9uECctHJvpIY0uWdKb1gTwchHUlB2Ll9jnuZL74+Q"
      "SuperBus__StoragePrefix": "superbus-sample-simple"
  
  tenant-b-connector-a:
    depends_on:
      superbus-worker:
        condition: service_healthy
    build:
      context: ./SuperBus.Samples.Simple.Connector
    environment:
      "SuperBus__Endpoint": "http://superbus-worker/api"
      "SuperBus__ConnectorId": "connector-a"
      "SuperBus__TenantId": "tenant-b"
      "SuperBus__SigningKey": "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgBhzsfVnKvBZjbyYxwXIIwgWqTXci9I+VIHSkO7xG7zChRANCAARy7cvTpFvs6gzm9rqj6o0+0fqoI24ahQBZOmRhQCNkLPNbzM5BJegdjlSTo4b35bl/UlU61T9IoSCBK/lBBPH0"
      "SuperBus__StoragePrefix": "superbus-sample-simple"

configs:
  azfunctions-secrets:
    content: |
      {
        "masterKey": {
          "name": "master",
          "value": "master-secret",
          "encrypted": false
        },
        "functionKeys": [
          {
            "name": "default",
            "value": "default-secret",
            "encrypted": false
          }
        ],
        "systemKeys": [
          {
            "name": "signalr_extension",
            "value": "signalr-secret",
            "encrypted": false
          }
        ],
      }