configs:
  signalr:
    content: |
      {
        "UpstreamSettings":
        {
          "Templates":
          [
            {
              "UrlTemplate": "http://superbus-worker/runtime/webhooks/signalr?code=master-secret",
              "EventPattern": "*",
              "HubPattern": "*",
              "CategoryPattern": "*"
            }
          ]
        }
      }